version: "3.8"

services:
  db:
    build: ./db
    environment:
      MYSQL_ROOT_PASSWORD: "password"
      DB_USERNAME: "myuser"
      DB_PASSWORD: "mypass"
      DB_DATABASE: "meals-app-db"
    ports:
      - "3306:3306"
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
      - mysql_data:/var/lib/mysql
    restart: unless-stopped
    healthcheck:
      test:
        [
          "CMD",
          "mysqladmin",
          "ping",
          "-h",
          "localhost",
          "-u${DB_USERNAME}",
          "-p${DB_PASSWORD}"
        ]
      interval: 5s
      timeout: 20s
      retries: 10

  backend:
    build: ./backend
    ports:
      - 3000:3000
    environment:
      DB_HOST: db
    restart: unless-stopped
    depends_on:
      db:
        condition: service_healthy

  frontend:
    build: ./frontend
    ports:
      - "3001:80"
    restart: unless-stopped

volumes:
  mysql_data:
